



var _IMAGE_TILER_COMPUTE_CLASS = '_IMAGE_TILER_USE_COMPUTED';


var _IMAGE_TILER_COMPUTE_ACTIONS  = [
    "_IMAGE_TILER_COMPUTE_NORMALIZE",
    "_IMAGE_TILER_COMPUTE_INVERSE",
    "_IMAGE_TILER_COMPUTE_LOG",
    "_IMAGE_TILER_COMPUTE_LAPLACIAN",
    "_IMAGE_TILER_COMPUTE_HIGHPASS"
];
